version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/iot-server/build/
permissions:
  - object: /home/ubuntu
    pattern: '**'
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: ./after-deploy.sh
      timeout: 300
      runas: ubuntu
